"""Prior geological models: Gaussian random fields of log-permeability, or the real Egg Model realizations."""
import glob
import os
import re

import numpy as np


def gaussian_field(nx, ny, corr_x, corr_y, angle_deg, rng):
    """
    Zero-mean, unit-variance Gaussian random field with an anisotropic Gaussian
    covariance, generated by FFT on a padded grid (spectral method).
    corr_x, corr_y : correlation lengths in cells along the rotated axes
    """
    px, py = 2 * nx, 2 * ny
    x = np.fft.fftfreq(px) * px
    y = np.fft.fftfreq(py) * py
    X, Y = np.meshgrid(x, y)
    th = np.deg2rad(angle_deg)
    xr = X * np.cos(th) + Y * np.sin(th)
    yr = -X * np.sin(th) + Y * np.cos(th)
    cov = np.exp(-(xr / corr_x) ** 2 - (yr / corr_y) ** 2)
    spec = np.sqrt(np.abs(np.fft.fft2(cov)))
    noise = rng.standard_normal((py, px))
    f = np.real(np.fft.ifft2(spec * np.fft.fft2(noise)))[:ny, :nx]
    return (f - f.mean()) / f.std()


def synthetic_ensemble(ne, nx=60, ny=60, mean_ln_md=np.log(500.0), sd_ln=1.0, seed=0):
    """
    Egg-inspired prior: elongated high-permeability trends (like channels) in a 60x60 grid.
    Returns ln(k [mD]) of shape (ne, ny, nx). Each member has its own orientation jitter.
    """
    rng = np.random.default_rng(seed)
    out = np.empty((ne, ny, nx))
    for e in range(ne):
        ang = 20.0 + rng.normal(0, 10)
        out[e] = mean_ln_md + sd_ln * gaussian_field(nx, ny, 18.0, 4.0, ang, rng)
    return out


# ---- Real Egg Model data (Jansen et al., 2014; 4TU.ResearchData) -----------------
def _read_eclipse_values(path):
    """Read every number in an ECLIPSE include file (handles '3*100.0' repeat syntax)."""
    vals = []
    with open(path, errors="ignore") as fh:
        for line in fh:
            line = line.split("--")[0]
            for tok in line.split():
                if tok == "/":
                    continue
                m = re.fullmatch(r"(\d+)\*([-+.\deE]+)", tok)
                if m:
                    vals.extend([float(m.group(2))] * int(m.group(1)))
                else:
                    try:
                        vals.append(float(tok.rstrip("/")))
                    except ValueError:
                        pass  # keyword such as PERMX
    return np.array(vals)


def load_egg_ensemble(egg_dir, nx=60, ny=60, nz=7):
    """
    Load the 101 Egg Model permeability realizations and the active-cell mask,
    collapsed to 2D by a geometric mean over the 7 layers.

    egg_dir : the unzipped Egg Model 'data.zip' folder (searched recursively).
    returns (ln_k [ne, ny, nx] in ln(mD), active [ny, nx] bool, file list)
    """
    files = [f for f in glob.glob(os.path.join(egg_dir, "**", "*"), recursive=True)
             if re.search(r"perm\D*\d+", os.path.basename(f), re.I) and os.path.isfile(f)]
    files.sort(key=lambda f: int(re.findall(r"\d+", os.path.basename(f))[-1]))
    if not files:
        raise FileNotFoundError(f"No PERM<n> files found under {egg_dir}")
    act_files = [f for f in glob.glob(os.path.join(egg_dir, "**", "*"), recursive=True)
                 if re.search(r"act", os.path.basename(f), re.I) and os.path.isfile(f)]
    active = np.ones((ny, nx), bool)
    if act_files:
        a = _read_eclipse_values(act_files[0])
        if a.size == nx * ny * nz:
            active = a.reshape(nz, ny, nx).max(0) > 0
    ens = []
    for f in files:
        v = _read_eclipse_values(f)
        if v.size != nx * ny * nz:
            continue
        k = np.maximum(v.reshape(nz, ny, nx), 1e-3)  # ECLIPSE order: i fastest, then j, then k
        ens.append(np.log(k).mean(0))                   # geometric mean over layers
    return np.array(ens), active, files
